# Generated by Django 3.0.8 on 2020-07-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edadata',
            old_name='CDlabel2Month',
            new_name='CDLabel2Month',
        ),
        migrations.RenameField(
            model_name='edadata',
            old_name='CDlabel4Month',
            new_name='CDLabel4Month',
        ),
        migrations.RenameField(
            model_name='edadata',
            old_name='job',
            new_name='job1',
        ),
    ]
